apiVersion: infra.k8smgmt.io/v3
kind: Namespace
metadata:
  name: test
  project: ankit
spec:
  drift:
    enabled: false
  limitRange:
    container: {}
    pod: {}
  placement:
    labels:
    - key: rafay.dev/clusterName
      value: mini-opa1
  resourceQuotas: {}
