apiVersion: infra.k8smgmt.io/v3
kind: Addon
metadata:
  name: test
  project: ankit
spec:
  artifact:
    artifact:
      paths:
      - name: file://artifacts/test/crd-constraint.yaml
    options: {}
    type: Yaml
  namespace: test
  sharing:
    enabled: false
  version: v1
