apiVersion: opa.k8smgmt.io/v3
kind: Constraint
metadata:
  labels:
    rafay.dev/opa: constraint
  name: test
  project: ankit
spec:
  artifact:
    artifact: {}
    options: {}
    type: Yaml
  templateName: one6
