apiVersion: gitops.k8smgmt.io/v3
kind: Pipeline
metadata:
  name: one
  project: ankit
spec:
  active: false
  sharing:
    enabled: false
  stages:
  - config:
      destinationRepo: {}
      includedResources:
      - name: OPAConstraint
      sourceAsDestination: true
    name: test
    type: SystemSync
