apiVersion: opa.k8smgmt.io/v3
kind: Policy
metadata:
  name: thhree
  project: ankit
spec:
  constraintList:
  - name: one
  installationParams:
    auditInterval: 25
    auditMatchKindOnly: true
    constraintViolationsLimit: 43
  sharing:
    enabled: false
  version: v1
