apiVersion: opa.k8smgmt.io/v3
kind: Policy
metadata:
  name: one1v
  project: ankit
spec:
  constraintList:
  - name: two
  installationParams:
    auditFromCache: true
    auditInterval: 12
    auditMatchKindOnly: true
    constraintViolationsLimit: 21
    enableDeleteOperations: true
  sharing:
    enabled: true
    projects:
    - name: defaultproject
    - name: nishant
  syncObjects:
  - group: j,
    kind: Pod
    version: v1
  version: v2
