apiVersion: infra.k8smgmt.io/v3
kind: Blueprint
metadata:
  name: addon
  project: ankit
spec:
  base:
    name: default
    version: 1.12.0
  customAddons:
  - dependsOn:
    - test2
    name: test
    version: v1
  - name: test2
    version: w
  defaultAddons:
    enableIngress: true
    enableLogging: true
    enableMonitoring: true
    enableVM: false
  drift:
    enabled: false
  opaPolicy:
    enabled: true
    name: one
    version: v23
  sharing:
    enabled: false
  version: v1w
