apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: sync-resource
  namespace: default
spec:
  encryptedData:
    credentials.password: AQBp3wN5Trst/PG02WzjGdxbapKQvrUPQZEO7JYGubbALCaKfDzg4j+GRQ9KQE3KIac+G8KMc+IpcrWyqIJEOOdy+tYoXaCJ+Tfppf0/cFo38sEO4TpP+5dEPxpjfVNKAwKOhmKyxLxmgieqPgNIobhQ3lGWhyX96kT4wrL7XQ5vFNpFJLXGjZHQsEUq1Otm6hWW+4JGaNYteLC5eSk85th1n6A9H+WRzOk/glB0neLGcDzB1M2ALzxeZV+gTzU4so+6gZjwsvbI1KzNGLbvghWskFOs7xnn4fWEziG9tp4rTyrsR+4Aa4K7PZCKt96NbrVU84S52J0cCGXNCNms+C3ReR4T5CvDxqLLbzTufwqR2VSKkiSE8JBBY6NqPuJIRS5Yt8suIxXbH0KAYnG9MAovlotnEDpVKCY=
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: sync-resource
      namespace: default

