apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: sync-resource
  namespace: default
spec:
  encryptedData:
    credentials.password: AQAwzvYbq/rI0Pcel7THs1Hv9KeCGfUc5liPunC2PYuBcDgKgsUwKjgst1ahKP7K1Z70I3U2tR1SKSPMic0Msowc4Dd2d4e+3rz4ioeRNfY/GHh3u00hnp2vgEMgJ1HOnvSD9DaLxJOno+SX6QPAFkkXyVVhCQ6owxuf7uzWePEzWyBwzTDr0SkikmN0d2BiZEZ72p5synf3g8h0BJVPXEMr3fMislUsKYma4NX3gO688ZRLxNGlAQqF/fi163ShwnLDAdvDz5MXW76m5yCPnI99YxpgO1Zdamp77Z3kIUvOGzLVIAfhZbBRge1MmcaO4chlM5Nih4+SE8UE0Pk3BXqKb4xodNbYu6yITtwqfyVnYd0nF/dYCQPHBdxChoej0i+4aOCLTApf8j6vuRTBGfr31Z0wrwVAAAY=
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: sync-resource
      namespace: default

