apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: sync-resource
  namespace: default
spec:
  encryptedData:
    credentials.password: AQBoo5nBBeCawCADfIzLUtW8R8EZ1fB4vu123WOroY46iOXDl7WXvycne1640dG/wklUKKRo8J5EPef7oeCw6ASPx+v7e4+32uSZ2r9DxvVIU4a7v5UjsGIMrXocuXiUCpB0bYKUDo4wGAytBTdw3p0CH8lvmYAhH/Q0g12MbZ3HgcgDMSSiTkGqooXebA946RPXduOJsSFqLaPlPkjt2PizTc4b2XnF25i6ZK3Stc/jCUd6KMFIqXJ5MsZ0xu0nVLySe+cjwp1bubArhjgM79pOVLOt0X7eQefZCKkEtITh3uJt+Rfw+m/QJk23p+QB9mnBmv74Fe2srgR6hBbZfFvKTFadRGq3VGhF2XezFPRMpSldLp+ycGNKPWfq95ASUPXztl83dvdfhcnExO39YGkdgmk7GblkWVk=
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: sync-resource
      namespace: default

