apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: sync-resource
  namespace: default
spec:
  encryptedData:
    credentials.password: AQC8p0qegomqROLrsbtk49cF79rFg1tU+UdotfFFn1S0Hkx906YsApJtwhM8mDXvMhI+vn+8uPn0Dm3elgtKeq3PBXmMnpDyblfwOZPdtlb6lvr/7ksKpavojNO0El54y+7gCtDuv958ge5PlvTXxS+IhJC9EHevHIlz+2s9I/ZR9a5FQBT4ISkVXJ6xOUpAlSa56Y36YZhJxqpmnWuaIQ4mNNjZpanaHORLiPMTu8MI1iZ7NgZCxf28y73n4yjQlGY8o0HI6nCr0NlaFBZ5IOPt2xZsvW47BX7+g/GhhILTrmnI/v0TGRxvwpjQHV2Hp1hSBHpmDPRcn7GKRJCq3Ulmk2uSduELekqdmu+NEFzfw/Q/B0rWnLd5KxSDQXtMqg3DJrKPMXXGnkE+ENxUydJw6hZy+qhRtKU=
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: sync-resource
      namespace: default

