apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: sync-resource
  namespace: default
spec:
  encryptedData:
    credentials.password: AQB3iS7DkOQpCPnMpNMqW1q30w1yBt3jwt3+J50D1v1FvvKC4cEkp/+H5CKu8kkm148QpQcpN279QV7Ahu3UnSlPbZYRGLl2D8YAaOLhCwlMvdDAun/TwVUtO13YThRPzb8UT5Is4ZDkxj1YxbFptmlmdStvS0pzsebwLB8wWDcH2VNbUr2lJ50IzOsYD+a1l65lMjcsqJ6UCuiKOt0ecaRhVNejC0aKnvlOSZ0p1QIw3ZgGQ5+tyVesPjdZx4Y5yFKB8bi6l8Y9g3MJLx15HR41AHRt5E5aoPLN0g69Xp7MzAIcG5iNhwFGjrTxRU6pCOJ1CNYdtfdKbvlMCFnJxLu8gp37q1tj0zhM9+Ayjgdx35XOMM/7WdB8tr7Pg4udMM9ww3h1mD0LslACdP17B1+ansUBFQvIQiI=
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: sync-resource
      namespace: default

