apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: sync-resource
  namespace: default
spec:
  encryptedData:
    credentials.password: AQBbU7H3Gnrp/QOix0xf8S69ZSzgFF5hNsbemP2DXRGFPbKmR6cdYGILaSKN1QtJlJISEsb/VB9HKtjIcz++lXQ+5C+e/3fZw8alNAeztbbWsCquV/8sSu3YQfVK30VfhcPDtuM7pg9icgNStkGjCcgPiEeq86HBJjOyG9o2ld+hRQEJRR/P0JK6C2Bjl5t4c4hpsQACZW/YueHrBPk0qWJh0pIP1Hv3EWjhRe0cw5og/nrTLwxplngJe/MSqspY7gtpvd+C3LGEtWgGhMVo/RYQj9kRfw0CN5znIBUbYKjrCy3FZB+TaaK+GJ9Xfz02UEndtQQnIek+plHJWHJ/6wD9Mb0+SD9JlTO0OXFN4KNasBy34UYhJ5VBjkeNCDKyxBuz+565+s8YsYQPlIyIXerw6bv3hT59yrc=
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: sync-resource
      namespace: default

