apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: sync-resource
  namespace: default
spec:
  encryptedData:
    credentials.password: AQB/+8qil20AxwbJBIcJ11zHtZqyF6qtZsFSyo8iwacKpcjrMvByRjFHjfagWhe1rd+fGnZJT2x73Z6xVf4O+rBAY5hVZ8dfw242hob7DHeOzp3sXfTPXbU9d+bcb0xfGOl51rQnmT+hvSi8DqCxfKXfOY8SD/vFVVTiRF4H/L7brlvhlMQ0z370PbPOpJlt6WE2OeoNsVT/6mCLT+k8mE0IdNN1Q90jPZSZ8qDPXUIHMHHkaYcZShql1V4Jcq6ish1b8Z7sNOHEEWQ9mx+y3VON/Ju9Pth68qqnL0cbbN4Morzc+q/ZBvZmxoE6+nObqDO93bvcA3nIFapoBQJEEuILg7XmbtDwkk06tnTo+VIqUfKJjZQQXrnDnz9JL+Jdl3qMGRteQ9YwmgOhBaC8hEj1ykLwtCLLqnE=
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: sync-resource
      namespace: default

