apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: sync-resource
  namespace: default
spec:
  encryptedData:
    credentials.password: AQAk3B4mHJD94OtksywvC6ZJUU761FGxZX9OegynDHX5reV9KHQLjR6rVGMJVVliOdXCZ/i5mcjY4O+2xlXQTjJRdAmGFnoCmo4GlDhpvDQfatKXCgRtSRAX8ajAX/Qc9piaApDt5D8VySV0Pqtn3MptgKtQKw+oNaYsysds6JBzgL5DFgh+h7+q6g8ZQmJtXCsafMcqTbjl4wLhKV8wASVSWGE5X6aKmnV0h0OYv6CX/6wxWXAke4iM4LoYjZKKYwPm6ZKQHlxQfv0YLmYRLClFx1qshMmoqlNGEMdbVp3qNIsl0TLxBjwwfNT9DAfimXmqAm5uW5NtfkmHHuD02+ii8emkjoaEOBv6FMT0l0CpuYXToXh+Ax0rzBImhYjaEdBIGcJQfZ4zDf33Rk0aa3K6/d4CLSkLbNg=
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: sync-resource
      namespace: default

