apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: sync-resource
  namespace: default
spec:
  encryptedData:
    credentials.password: AQAdenw5j+ZoZjQLC2RmOAzjknpS6NQL0OhM8PPnGkkPCWotPOKroqxyd78ZYWkPj1StrElSaOiZJ9DxJpM6Ba9but0ydyV9GlLnrhpkFD+0wez81fmxdOz2Fb7+8hLRciCqljdWVksKBH//Unyykf/9rHNu0HUXZciMdnrRijxsy/TDTP7Fvp4OL0fO0MvQEAXzbOo9JJcixTnq3LMdou0QdsAVDcWMSrohY52tsFfZXBNWBj+DEEkFsGnMZANWO2UCu2+7w3RWO1dYijIx4oaAdjv7FQ6f9uLMXsWnKK60CMkkfJvOvoU5eKC0Xf+Vs8bt+hhr4p2wuYUtmyug0Yg4qUIC83IXD7GpPca+u0BcwfkHt7dR7CiD7yxd1xIlQnmdrWrE33y/jp2voZHoJBIcrY19KDis8DU=
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: sync-resource
      namespace: default

